services:
  ds-server:
    build: .
    ports:
      - "4000:3000"
    command: npm start
    restart: unless-stopped
    depends_on:
      - ds-db
    environment:
      DB_HOST: ds-db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: DataStructure

  ds-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: DataStructure
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  db_data:
    driver: local
